apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-debug
spec:
  workspaces:
  - name: output
    optional: true
  steps:
  - image: alpine:latest
    workingDir: "/workspace/output/"
    script: |
      ls -lrt  

       
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sqr-yard-be
spec:
  params:
    - name: gitrevision-tag
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    params:
    - name: url
<<<<<<< HEAD:be-pipeline.yaml
      value: "http://gitlab.squareyards.com:8180/dotcom/zelarsoft-code-api.git"
=======
      value: "<repo-url>"
>>>>>>> 83681fe8c4f0555503d080a6a69588e41678426c:tekton-pipeline.yaml
    - name: revision
      value: $(params.gitrevision-tag)    
    workspaces:
    - name: output
      workspace: shared-data     
  - name: debug-folder
    runAfter: ["fetch-repo"]
    taskRef:
      name: run-debug 
    workspaces:
    - name: output
      workspace: shared-data         
  - name: build-container-image
    runAfter: ["debug-folder"]
    taskRef:
      name: build-kaniko-git
    params:
    - name: app_repo
      value: dir:///workspace/output/
    - name: container_image
      value: <image-name> 
    - name: container_tag
      value: $(params.gitrevision-tag)
    workspaces:
    - name: output
<<<<<<< HEAD:be-pipeline.yaml
      workspace: shared-data
=======
      workspace: shared-data
>>>>>>> 83681fe8c4f0555503d080a6a69588e41678426c:tekton-pipeline.yaml
