apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: git-clone-checking-fe
spec:
  serviceAccountName: build-robot
  pipelineRef:
    name: sqr-yard-fe
  workspaces:
  - name: shared-data-fe
    volumeClaimTemplate:
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
