apiVersion: v1
kind: Secret
metadata:
  name: basic-user-pass
  annotations:
    tekton.dev/git-0: http://gitlab.squareyards.com:8180 # Described below
type: kubernetes.io/basic-auth
stringData:
  username: harish
  password: 7038510717@h