apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: cluster-reader
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["secrets", "configmaps", "services"]
  verbs: ["get", "watch", "list", "create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: apps-reader
rules:
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments", "replicasets"]
  verbs: ["get", "watch", "list", "create"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: autoscaling-reader
rules:
- apiGroups: ["autoscaling"] # "" indicates the core API group
  resources: ["horizontalpodautoscalers"]
  verbs: ["get", "watch", "list", "create"]

--- 

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata: 
  name: network-reader
rules:
- apiGroups: ["networking.k8s.io"] # "" indicates the core API group
  resources: ["ingresses"]
  verbs: ["get", "watch", "list", "create"]