---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret-fe
type: Opaque
stringData:
  secretToken: "1234567890"

# ---
# apiVersion: triggers.tekton.dev/v1beta1
# kind: EventListener
# metadata:
#   name: gitlab-event-listener-fe
#   # annotations:
#   #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: https
# spec:
#   serviceAccountName: build-robot
#   triggers:
#     - triggerRef: gitlab-listener-trigger-fe
#   resources:
#     kubernetesResource:
#        serviceType: NodePort
#       serviceType: LoadBalancer
#       servicePort: 8128

---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: gitlab-listener-trigger-fe
spec:
  interceptors:
    - name: "verify-gitlab-payload"
      ref:
        name: "gitlab"
        kind: ClusterInterceptor
      params:
        - name: secretRef
          value:
            secretName: "gitlab-secret-fe"
            secretKey: "secretToken"
        - name: eventTypes
          value:
            - "Push Hook"
            - "Tag Push Hook"
    - name: "CEL filter: only when PRs are opened"
      ref:
        name: "cel"
      params:
      -  name: "overlays"  
         value:         
         - key: branch_name
           expression: "body.ref.split('/')[2]"            
  bindings:
    - ref: binding-fe
  template:
    ref: template-fe

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding-fe
spec:
  params:
    - name: gitrevision-tag
      value: $(extensions.branch_name)

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template-fe
spec:
  params:
    - name: gitrevision-tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: sqr-yard-fe-pipeline-run-
      spec:
        serviceAccountName: build-robot
        pipelineRef:
          name: sqr-yard-fe
        params: 
        - name: gitrevision-tag
          value: $(tt.params.gitrevision-tag)       
        workspaces:
        - name: shared-data-fe
          volumeClaimTemplate:
            spec:
              accessModes:
                - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi