---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
stringData:
  secretToken: "1234567"

---
apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: gitlab-event-listener
spec:
  serviceAccountName: build-robot
  triggers:
    - triggerRef: gitlab-listener-trigger
    - triggerRef: gitlab-listener-trigger-fe
  resources:
    kubernetesResource:
      serviceType: NodePort

---
apiVersion: triggers.tekton.dev/v1beta1
kind: Trigger
metadata:
  name: gitlab-listener-trigger
spec:
  interceptors:
    - name: "verify-gitlab-payload-be"
      ref:
        name: "gitlab"
        kind: ClusterInterceptor
      params:
        - name: secretRef
          value:
            secretName: "gitlab-secret"
            secretKey: "secretToken"
        - name: eventTypes
          value:
            - "Push Hook"
            - "Tag Push Hook"

    - name: "CEL filter: only when PRs are opened"
      ref:
        name: "cel"
      params:
      -  name: "overlays"  
         value:         
         - key: branch_name
           expression: "body.ref.split('/')[2]"
  bindings:
    - ref: binding
  template:
    ref: template

---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: gitrevision-tag
      value: $(extensions.branch_name)      


---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: gitrevision-tag
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
         generateName: yard-be-pipeline-run-
      spec:
        serviceAccountName: build-robot
        pipelineRef:
          name: yard-be  
        params: 
        - name: gitrevision-tag
          value: $(tt.params.gitrevision-tag)                 
        workspaces:  
        - name: shared-data 
          volumeClaimTemplate:
            spec:
              accessModes:
              - ReadWriteOnce
              resources:
                requests:
                  storage: 1Gi           