apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-debug
spec:
  workspaces:
  - name: output
    optional: true
  steps:
  - image: alpine:latest
    workingDir: "/workspace/output/"
    script: |
      ls -lrt      
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: sqr-yard-fe
  # annotations:
  #   tekton.dev/pipelines.minVersion: '0.12.1'
  #   tekton.dev/tags: build, push, deploy
  #   tekton.dev/platforms: "linux/amd64"
spec:
  params:
  - name: gitrevision-tag
  workspaces:
  - name: shared-data-fe
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: fetch-repo-fe
    taskRef:
      name: git-clone
    params:
    - name: url
      value: "http://gitlab.squareyards.com:8180/dotcom/zelarsoft-code.git"
    - name: revision
      value: $(params.gitrevision-tag) 
    workspaces:
    - name: output
      workspace: shared-data-fe
  - name: debug-folder-fe
    runAfter: ["fetch-repo-fe"]
    taskRef:
      name: run-debug
    workspaces:
    - name: output
      workspace: shared-data-fe     
  - name: build-container-image-fe
    runAfter: ["debug-folder-fe"]
    taskRef:
      name: build-kaniko-git
    params:
    - name: app_repo
      value: dir:///workspace/output/
    - name: container_image
      value: asia-south1-docker.pkg.dev/zelarsoft-350108/sqyards/front-end-image
    - name: container_tag
      value: $(params.gitrevision-tag)
    workspaces:
    - name: output
      workspace: shared-data-fe
