server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push
  - url: http://loki-svc.<ip>.nip.io/loki/api/v1/push

scrape_configs:
- job_name: VM3
  static_configs:
  - targets:
      - localhost
    labels:
      job: VM3
      __path__: /var/log/*log
      host: grafana
