apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-debug
spec:
  workspaces:
  - name: output
    optional: true
  steps:
  - image: alpine:latest
    workingDir: "/workspace/output/"
    script: |
      ls -lrt      
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  workspaces:
  - name: shared-data
    description: |
      This workspace will receive the cloned git repo and be passed
      to the next Task for the repo's README.md file to be read.
  tasks:
  - name: fetch-repo
    taskRef:
      name: git-clone
    params:
    - name: url
      value: "<repo-url>"
    - name: revision
      value: "main"   
    workspaces:
    - name: output
      workspace: shared-data
  - name: debug-folder
    runAfter: ["fetch-repo"]
    taskRef:
      name: run-debug 
    workspaces:
    - name: output
      workspace: shared-data      
  - name: deploy-to-gke
    runAfter: ["debug-folder"]
    taskRef:
      name: deploy-task
    params:
    - name: charts_dir
      value: /workspace/output/ujji
    - name: release_version
      value: v0.1.0
    - name: release_name
      value: ujji
    - name: release_namespace
      value: default
    - name: values_file
      value: dev-values.yaml
    workspaces:
    - name: output
      workspace: shared-data 
