apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: deploy-run
spec:
  serviceAccountName: build-robot
  pipelineRef:
    name: deploy-pipeline
  params:
  - name: charts_dir
    value: /workspace/output/ujji
  - name: release_version
    value: v0.1.0
  - name: release_name
    value: ujji
  workspaces:
  - name: shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 500Mi
