apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: sqrd-deploy-task
  labels:
    app.kubernetes.io/version: "0.3"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/categories: Deployment
    tekton.dev/tags: helm
    tekton.dev/platforms: "linux/amd64,linux/s390x,linux/ppc64le,linux/arm64"
spec:
  params:
    - name: charts_dir
      description: The directory in source that contains the helm chart
    - name: release_version
      description: The helm release version in semantic versioning format
      default: "v0.1.0"
    - name: release_name
      description: The helm release name
      default: "sqyards"
    - name: release_namespace
      description: The helm release namespace
      default: "default"
    - name: values_file
      description: "The values file to be used"
      default: "dev-values.yaml"
  workspaces:
    - name: output
  steps:
    - name: upgrade
      image: docker.io/lachlanevenson/k8s-helm
      workingDir: /workspace/output
      script: |
        echo current installed helm releases
        helm list --namespace "$(params.release_namespace)"
        helm list -A

        echo installing helm chart...
        helm upgrade --install --wait --values "$(params.charts_dir)/$(params.values_file)" --namespace "$(params.release_namespace)" --version "$(params.release_version)" "$(params.release_name)" "$(params.charts_dir)" --debug
